name: Self Tests

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Base Branch match returns configured output
            base: ${{ github.ref_name}}
            pattern: .*
            flags: ""
            output-on-base: test
            expected-output: test
            change-file: ""
          - name: Comparison to main produces expected output
            base: main
            pattern: .*
            flags: ""
            output-on-base: base
            expected-output: ${{ github.ref_name == 'main' && 'base' || 'true' }}
            change-file: ""
          - name: When change exists then change detected
            base: main
            pattern: .*
            flags: ""
            output-on-base: base
            require-non-base: true
            expected-output: true
            change-file: test-file
          - name: When irrelevant change exists then change not detected
            base: main
            pattern: .md
            flags: -F
            output-on-base: base
            require-non-base: true
            expected-output: false
            change-file: test.txt
    name: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Introduce fake change
        if: ${{ matrix.change-file != '' }}
        shell: bash
        run: |
          echo "test" >> ${{ matrix.change-file }}
          git add ${{ matrix.change-file }}
          git config --global user.email "test@example.org"
          git config --global user.name "Test[bot]"
          git commit -m "Introducing changed file"

      - name: Run action
        id: change-detection
        if: ${{ matrix.require-non-base != true || github.ref_name != matrix.base }}
        uses: rvesse/detect-changes-action@v1
        with:
          base: ${{ matrix.base}}
          pattern: ${{ matrix.pattern}}
          flags: ${{ matrix.flags }}
          output-on-base: ${{ matrix.output-on-base}}

      - name: Verify default output
        if: ${{ matrix.require-non-base != true || github.ref_name != matrix.base }}
        run: |
          if [ "${{ steps.change-detection.outputs.changed}}" != "${{ matrix.expected-output}}" ]; then
            echo "::error::Change Detection output not expected value ${{ matrix.expected-output }}, got ${{ steps.change-detection.outputs.changed }}"
            exit 1
          fi

      - name: Note when test skipped
        if: ${{ matrix.require-non-base == true && github.ref_name == matrix.base }}
        run: |
          echo "::notice::Test skipped as requires non-base branch for test but running on configured base branch"
