name: Self Tests

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - base: ${{ github.ref_name}}
            pattern: .*
            flags: ""
            output-on-base: test
            expected-output: test
            change-file: ""
          - base: main
            pattern: .*
            flags: ""
            output-on-base: base
            expected-output: ${{ github.ref_name == 'main' && 'base' || 'true' }}
            change-file: ""
          - base: main
            pattern: .*
            flags: ""
            output-on-base: base
            expected-output: true
            change-file: test-file
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Introduce fake change
        if: ${{ matrix.change-file != '' }}
        shell: bash
        run: |
          echo "test" >> ${{ matrix.change-file }}
          git commit -m "Test" --author "Test <test@example.org>"

      - name: Run action
        id: change-detection
        uses: rvesse/detect-changes-action@v1
        with:
          base: ${{ matrix.base}}
          pattern: ${{ matrix.pattern}}
          flags: ${{ matrix.flags }}
          output-on-base: ${{ matrix.output-on-base}}

      - name: Verify default output
        run: |
          if [ "${{ steps.change-detection.outputs.changed}}" != "${{ matrix.expected-output}}" ]; then
            echo "::error::Change Detection output not expected value ${{ matrix.expected-output }}, got ${{ steps.change-detection.outputs.changed }}"
          fi
